#!/bin/bash

# Script to create draft pull requests for Secret variable support branches

set -e

echo "Creating draft PRs for Secret variable support branches..."
echo ""

# Set the default repository
echo "Setting default repository..."
gh repo set-default robotframework/robotframework
echo ""

# # PR 1: OperatingSystem Library
# echo "1. Creating PR for OperatingSystem library (5512-os-run-secret)..."
# git checkout 5512-os-run-secret
# gh pr create --draft --title "Add Secret variable support to OperatingSystem run and create_binary_file keywords" --body "## Summary
# This PR adds \`Secret\` variable support to additional OperatingSystem library keywords to prevent sensitive data from appearing in logs.

# ## Changes
# - **\`run()\`, \`run_and_return_rc()\`, \`run_and_return_rc_and_output()\`**: Command parameter now accepts Secret variables. Secret commands are logged as \`<redacted>\` instead of showing the full command.
# - **\`create_binary_file()\`**: Content parameter now accepts Secret variables for safe handling of binary secrets like private keys and certificates.

# ## Tests
# - Added comprehensive test cases for all new Secret functionality
# - All tests verify that secrets are not logged
# - All 8 secret-related tests passing ✅

# ## Notes
# ⚠️ **This code was generated by Claude Code and requires human review before merging.**

# The implementation follows the same pattern used in the base branch (#5512) for \`create_file()\`, \`append_to_file()\`, and environment variable keywords.

# ## Related
# - Base PR: #5512
# - Related branches: \`5512-telnet-secret\`, \`5512-process-secret\`"

# echo "✅ OperatingSystem PR created"
# echo ""

# PR 2: Telnet Library

echo "2. Creating PR for Telnet library (5512-telnet-secret)..."
git checkout 5512-telnet-secret
gh pr create --draft --title "Add Secret variable support to Telnet library keywords" --body "## Summary
This PR adds \`Secret\` variable support to Telnet library keywords to prevent credentials and sensitive commands from appearing in logs.

## Changes
- **\`login()\`**: username and password parameters now accept Secret variables
- **\`write()\` and \`write_bare()\`**: text parameter now accepts Secret variables for safe handling of sensitive commands
- **\`execute_command()\`**: command parameter now accepts Secret variables to prevent commands with passwords/keys from being logged
- **\`write_until_expected_output()\`**: text parameter now accepts Secret variables

## Tests
- Added comprehensive test cases for all Secret functionality
- Tests verify that secrets are not logged
- Tests verify functionality works correctly with Secret variables
- ⚠️ Tests require telnet server infrastructure to run (tagged \`no-ci\`)

## Notes
⚠️ **This code was generated by Claude Code and requires human review before merging.**

The implementation extracts Secret values before processing, ensuring seamless integration with existing functionality while preventing sensitive data from being logged.

## Related
- Base PR: #5512
- Related branches: \`5512-os-run-secret\`, \`5512-process-secret\`"

echo "✅ Telnet PR created"
echo ""

# PR 3: Process Library
echo "3. Creating PR for Process library (5512-process-secret)..."
git checkout 5512-process-secret
gh pr create --draft --title "Add Secret variable support to Process library keywords" --body "## Summary
This PR adds \`Secret\` variable support to Process library keywords to prevent API keys, passwords, and tokens from appearing in logs.

## Changes
- **\`run_process()\` and \`start_process()\`**: Environment variable values now accept Secret (both \`env\` dict and \`env:*\` keyword arguments)
- **\`run_process()\` and \`start_process()\`**: stdin parameter now accepts Secret variables
- Implementation in ProcessConfiguration class:
  - \`_get_stdin()\` extracts Secret value before processing
  - \`_get_initial_env()\` handles Secret values in env dictionary
  - \`_add_to_env()\` handles Secret values in env:* keyword arguments

## Tests
- Added comprehensive test cases for all Secret functionality
- Tests for env dict with Secret values
- Tests for env:* keyword args with Secret values
- Tests for stdin with Secret values
- All tests verify functionality works correctly and secrets are not logged
- All 3 secret-related tests passing ✅

## Notes
⚠️ **This code was generated by Claude Code and requires human review before merging.**

The implementation extracts Secret values before processing, ensuring seamless integration with existing functionality while preventing sensitive data from being logged.

## Related
- Base PR: #5512
- Related branches: \`5512-os-run-secret\`, \`5512-telnet-secret\`"

echo "✅ Process PR created"
echo ""

echo "All draft PRs created successfully! 🎉"
echo ""
echo "The PRs will trigger CI pipeline tests automatically."
