[tool.mypy]
allow_redefinition = true
show_error_codes = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = "robot.*"

[[tool.mypy.overrides]]
module = "robot.model.testcase"
strict_equality = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "robot.api.*"
strict_equality = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_untyped_defs = true
