// Development fixture rendered by `npm start`, generated with Libdoc from
// libdoc/DevLibrary.py. Add a case to the UI by adding a keyword there.
//
// Do not edit by hand: run `npm run testdata`, or just save DevLibrary.py
// while `npm start` is running.
import type { Libdoc } from "./types";

const DATA: Libdoc = {
  specversion: 4,
  name: "DevLibrary",
  doc: '<p>Library for developing the Libdoc HTML frontend.</p>\n<div class="toc">\n<ul>\n<li><a href="#purpose">Purpose</a></li>\n<li><a href="#what-is-covered">What is covered</a></li>\n<li><a href="#formatting-examples">Formatting examples</a><ul>\n<li><a href="#lists">Lists</a></li>\n<li><a href="#code-blocks">Code blocks</a></li>\n</ul>\n</li>\n</ul>\n</div>\n<h2 id="purpose">Purpose</h2>\n<p>This library exists only to produce the development fixture rendered by\n<code>npm start</code>. It is not shipped and it is not used by any test. Every keyword\nhere earns its place by exercising something the frontend renders, so adding a\nkeyword is how you add a case to the fixture.</p>\n<p>Keywords are named after the case they present rather than after anything a\nbrowser library would do. The library is not pretending to be a real one, and\na name that says what is being rendered is easier to find when a rendering\nbug needs reproducing. What the keywords <em>accept and return</em> is a different\nmatter: do not add types, argument kinds or documentation structures that a\nreal library could not produce, because the point is to render what Libdoc\nactually receives.</p>\n<p>Run <code>npm run testdata</code> to regenerate <code>testdata.ts</code> from this file. The dev\nserver does it for you whenever this file is saved.</p>\n<p><code>DevLibraryRobotFormat.py</code> is the counterpart of this library for the ROBOT\ndocumentation format, and covers the documentation tables only that format\nproduces.</p>\n<h2 id="what-is-covered">What is covered</h2>\n<table>\n<thead>\n<tr>\n<th>Case</th>\n<th>Keywords</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Type aliases</td>\n<td><a href="#Alias%20Inside%20Generic%20Type" title="&quot;Alias Inside Generic Type&quot; keyword">Alias Inside Generic Type</a>, <a href="#Alias%20Of%20None" title="&quot;Alias Of None&quot; keyword">Alias Of None</a>, <a href="#Alias%20Of%20Union" title="&quot;Alias Of Union&quot; keyword">Alias Of Union</a>, <a href="#Deeply%20Nested%20Aliases" title="&quot;Deeply Nested Aliases&quot; keyword">Deeply Nested Aliases</a>, <a href="#Parameterized%20Alias" title="&quot;Parameterized Alias&quot; keyword">Parameterized Alias</a>, <a href="#Recursive%20Alias" title="&quot;Recursive Alias&quot; keyword">Recursive Alias</a></td>\n</tr>\n<tr>\n<td>Enums</td>\n<td><a href="#Enum%20Arguments" title="&quot;Enum Arguments&quot; keyword">Enum Arguments</a>, <a href="#Enum%20With%20Integer%20Values" title="&quot;Enum With Integer Values&quot; keyword">Enum With Integer Values</a></td>\n</tr>\n<tr>\n<td>Literals</td>\n<td><a href="#Literal%20With%20Mixed%20Types" title="&quot;Literal With Mixed Types&quot; keyword">Literal With Mixed Types</a></td>\n</tr>\n<tr>\n<td>TypedDicts</td>\n<td><a href="#Alias%20Of%20TypedDict" title="&quot;Alias Of TypedDict&quot; keyword">Alias Of TypedDict</a>, <a href="#TypedDict%20Argument%20And%20Return" title="&quot;TypedDict Argument And Return&quot; keyword">TypedDict Argument And Return</a></td>\n</tr>\n<tr>\n<td>Custom types</td>\n<td><a href="#Custom%20Type%20Documented%20By%20Class" title="&quot;Custom Type Documented By Class&quot; keyword">Custom Type Documented By Class</a>, <a href="#Custom%20Type%20With%20Converter%20Method" title="&quot;Custom Type With Converter Method&quot; keyword">Custom Type With Converter Method</a></td>\n</tr>\n<tr>\n<td>Generics</td>\n<td><a href="#Nested%20Generic%20Type" title="&quot;Nested Generic Type&quot; keyword">Nested Generic Type</a></td>\n</tr>\n<tr>\n<td>Argument kinds</td>\n<td><a href="#All%20Argument%20Kinds" title="&quot;All Argument Kinds&quot; keyword">All Argument Kinds</a>, <a href="#No%20Arguments" title="&quot;No Arguments&quot; keyword">No Arguments</a></td>\n</tr>\n<tr>\n<td>Argument documentation</td>\n<td><a href="#Long%20Argument%20Documentation" title="&quot;Long Argument Documentation&quot; keyword">Long Argument Documentation</a></td>\n</tr>\n<tr>\n<td>Returns and raises</td>\n<td><a href="#Returns%20And%20Raises" title="&quot;Returns And Raises&quot; keyword">Returns And Raises</a></td>\n</tr>\n<tr>\n<td>Deprecation</td>\n<td><a href="#Deprecated%20Keyword" title="&quot;Deprecated Keyword&quot; keyword">Deprecated Keyword</a></td>\n</tr>\n</tbody>\n</table>\n<div class="admonition note">\n<p class="admonition-title">Note</p>\n<p>Documentation is written in Markdown, so this text also covers the Markdown\nfeatures the frontend has to render. Each row of the table above is one\nsource line: a row wrapped onto a second line becomes a second row.</p>\n</div>\n<div class="admonition tip">\n<p class="admonition-title">Admonitions have optional titles</p>\n<p>And they nest:</p>\n<div class="admonition warning">\n<p class="admonition-title">Warning</p>\n<p>Do not add cases here that a real library could not produce.</p>\n</div>\n</div>\n<h2 id="formatting-examples">Formatting examples</h2>\n<p>Basic formatting such as <strong>bold</strong>, <em>italics</em> and <code>code</code> works, and so do links\nto keywords like <a href="#Returns%20And%20Raises" title="&quot;Returns And Raises&quot; keyword">Returns And Raises</a>, to types like <a href="#type-integer" title="&quot;integer&quot; type">int</a> and to sections like\n<a href="#purpose" title="&quot;Purpose&quot; section">Purpose</a>.</p>\n<h3 id="lists">Lists</h3>\n<ul>\n<li>Unordered item.<ul>\n<li>Nested item.</li>\n<li>Another nested item.</li>\n</ul>\n</li>\n<li>Item with an ordered sublist.<ol>\n<li>First.</li>\n<li>Second.</li>\n</ol>\n</li>\n</ul>\n<h3 id="code-blocks">Code blocks</h3>\n<div class="code"><pre><span></span><code><span class="gh">*** Test Cases ***</span>\n<span class="gu">Example</span>\n<span class="p">    </span><span class="nf">Enum Arguments</span><span class="p">    </span><span class="s">id=submit</span><span class="p">    </span><span class="s">button=right</span>\n</code></pre></div>',
  version: "1.2.3",
  generated: "2024-01-01T00:00:00+00:00",
  type: "LIBRARY",
  scope: "GLOBAL",
  docFormat: "HTML",
  source: "src/web/libdoc/DevLibrary.py",
  lineno: 126,
  tags: [
    "aliases",
    "arguments",
    "custom types",
    "deprecation",
    "enums",
    "generics",
    "literals",
    "returns",
    "typeddicts",
  ],
  inits: [
    {
      name: "__init__",
      doc: "<p>Configures the library when it is imported.</p>",
      shortdoc: "Configures the library when it is imported.",
      args: [
        {
          name: "browser",
          doc: "<p>a union of an enum and a standard type.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "MouseButton",
                typedoc: "MouseButton",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "chromium",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "browser: MouseButton | str = chromium",
        },
        {
          name: "timeout",
          doc: "<p>a type Libdoc renders with a converter of its own.</p>",
          type: {
            name: "timedelta",
            typedoc: "timedelta",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "0:00:10",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "timeout: timedelta = 0:00:10",
        },
        {
          name: "options",
          doc: "<p>an optional generic type.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "dict",
                typedoc: "dictionary",
                nested: [
                  {
                    name: "str",
                    typedoc: "string",
                    nested: [],
                    union: false,
                    alias: null,
                  },
                  {
                    name: "str",
                    typedoc: "string",
                    nested: [],
                    union: false,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "options: dict[str, str] | None = None",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 203,
    },
  ],
  keywords: [
    {
      name: "Alias Inside Generic Type",
      doc: "<p>Takes an alias nested inside a generic type.</p>",
      shortdoc: "Takes an alias nested inside a generic type.",
      args: [
        {
          name: "selectors",
          doc: "<p>the alias is nested inside <code>list</code>.</p>",
          type: {
            name: "list",
            typedoc: "list",
            nested: [
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: "Locator",
              },
            ],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selectors: list[Locator]",
        },
        {
          name: "duration",
          doc: "<p>a type Libdoc renders with a converter of its own.</p>",
          type: {
            name: "timedelta",
            typedoc: "timedelta",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "0:00:02",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "duration: timedelta = 0:00:02",
        },
      ],
      returnType: {
        name: "int",
        typedoc: "integer",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>How many elements matched.</p>",
      raises: {},
      tags: ["aliases"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 259,
    },
    {
      name: "Alias Of None",
      doc: "<p>Returns an alias of <code>None</code>.</p>\n<p>A keyword returning plain <code>None</code> shows no return type at all, because\nevery Python function returns <code>None</code> implicitly, but this alias was\ndeclared and annotated on purpose.</p>",
      shortdoc: "Returns an alias of `None`.",
      args: [],
      returnType: {
        name: "None",
        typedoc: "None",
        nested: [],
        union: false,
        alias: "Nothing",
      },
      returnDoc: "",
      raises: {},
      tags: ["aliases", "returns"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 514,
    },
    {
      name: "Alias Of TypedDict",
      doc: "<p>Takes an alias of a TypedDict.</p>\n<p>The name is set with <code>@keyword</code>, because the one derived from the method\nname would lose the capital <code>D</code>.</p>",
      shortdoc: "Takes an alias of a TypedDict.",
      args: [
        {
          name: "path",
          doc: "<p>a plain string.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "path: str",
        },
        {
          name: "margins",
          doc: "<p>uses an alias of a TypedDict.</p>",
          type: {
            name: "PdfMargins",
            typedoc: "PdfMargins",
            nested: [],
            union: false,
            alias: "Margins",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "margins: Margins",
        },
        {
          name: "scale",
          doc: "<p>a plain float.</p>",
          type: {
            name: "float",
            typedoc: "float",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "1.0",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "scale: float = 1.0",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["aliases", "typeddicts"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 296,
    },
    {
      name: "Alias Of Union",
      doc: "<p>Takes and returns an alias of a union.</p>\n<p>A union has no single type to document, which is what this case is here\nto show.</p>",
      shortdoc: "Takes and returns an alias of a union.",
      args: [
        {
          name: "handle",
          doc: "<p>uses an alias of a union.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "Popen",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: "Handle",
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "handle: Handle = None",
        },
      ],
      returnType: {
        name: "Union",
        typedoc: null,
        nested: [
          {
            name: "Popen",
            typedoc: null,
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "None",
            typedoc: "None",
            nested: [],
            union: false,
            alias: null,
          },
        ],
        union: true,
        alias: "Handle",
      },
      returnDoc: "<p>The previous handle.</p>",
      raises: {},
      tags: ["aliases"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 357,
    },
    {
      name: "All Argument Kinds",
      doc: "<p>Has every kind of argument there is.</p>\n<p>No real keyword has all of them at once, which is why this one is named\nfor the case rather than for anything it could plausibly do.</p>",
      shortdoc: "Has every kind of argument there is.",
      args: [
        {
          name: "a",
          doc: "<p>positional-only argument.</p>",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_ONLY",
          required: true,
          repr: "a",
        },
        {
          name: "",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_ONLY_MARKER",
          required: false,
          repr: "/",
        },
        {
          name: "b",
          doc: "<p>normal argument, whose documentation\ncontinues on the next line.</p>",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "b",
        },
        {
          name: "c",
          doc: "<p>normal argument with a default value.</p>",
          type: null,
          defaultValue: "d",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "c=d",
        },
        {
          name: "e",
          doc: "<p>free positional arguments.</p>",
          type: null,
          defaultValue: null,
          kind: "VAR_POSITIONAL",
          required: false,
          repr: "*e",
        },
        {
          name: "f",
          doc: "<p>named-only argument without a default value.</p>",
          type: null,
          defaultValue: null,
          kind: "NAMED_ONLY",
          required: true,
          repr: "f",
        },
        {
          name: "g",
          doc: "<p>named-only argument with a default value.</p>",
          type: null,
          defaultValue: "h",
          kind: "NAMED_ONLY",
          required: false,
          repr: "g=h",
        },
        {
          name: "i",
          doc: "<p>free named arguments.</p>",
          type: null,
          defaultValue: null,
          kind: "VAR_NAMED",
          required: false,
          repr: "**i",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["arguments"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 487,
    },
    {
      name: "Custom Type Documented By Class",
      doc: "<p>Takes a custom type documented by the class itself.</p>\n<p>The class is its own converter here, so its documentation is used.</p>",
      shortdoc: "Takes a custom type documented by the class itself.",
      args: [
        {
          name: "credential",
          doc: "<p>uses a custom type documented by its class.</p>",
          type: {
            name: "Credential",
            typedoc: "Credential",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "credential: Credential",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["custom types"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 458,
    },
    {
      name: "Custom Type With Converter Method",
      doc: "<p>Takes a custom type whose converter method is documented.</p>\n<p>The documentation comes from <code>SelectorSpec.parse</code> rather than from the\nclass, because the converter is registered separately.</p>",
      shortdoc: "Takes a custom type whose converter method is documented.",
      args: [
        {
          name: "selector",
          doc: "<p>uses a custom type documented by its converter.</p>",
          type: {
            name: "SelectorSpec",
            typedoc: "SelectorSpec",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selector: SelectorSpec",
        },
      ],
      returnType: {
        name: "SelectorSpec",
        typedoc: "SelectorSpec",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The parsed selector.</p>",
      raises: {},
      tags: ["custom types"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 441,
    },
    {
      name: "Deeply Nested Aliases",
      doc: "<p>Takes aliases nested inside other types and inside each other.</p>\n<p>This is the deepest type the UI renders.</p>",
      shortdoc:
        "Takes aliases nested inside other types and inside each other.",
      args: [
        {
          name: "target",
          doc: "<p>aliases nested inside other types and inside each other.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "SelectorSpec",
                typedoc: "SelectorSpec",
                nested: [],
                union: false,
                alias: "WebElement",
              },
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "list",
                typedoc: "list",
                nested: [
                  {
                    name: "Union",
                    typedoc: null,
                    nested: [
                      {
                        name: "SelectorSpec",
                        typedoc: "SelectorSpec",
                        nested: [],
                        union: false,
                        alias: "WebElement",
                      },
                      {
                        name: "str",
                        typedoc: "string",
                        nested: [],
                        union: false,
                        alias: null,
                      },
                      {
                        name: "list",
                        typedoc: "list",
                        nested: [
                          {
                            name: "str",
                            typedoc: "string",
                            nested: [],
                            union: false,
                            alias: "Locator",
                          },
                        ],
                        union: false,
                        alias: null,
                      },
                    ],
                    union: true,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "target: WebElement | str | list[WebElement | str | list[Locator]]",
        },
        {
          name: "smooth",
          doc: "<p>a plain boolean, for contrast.</p>",
          type: {
            name: "bool",
            typedoc: "boolean",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "True",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "smooth: bool = True",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["aliases"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 278,
    },
    {
      name: "Deprecated Keyword",
      doc: '<p><em>DEPRECATED</em> Use <a href="#Enum%20Arguments" title="&quot;Enum Arguments&quot; keyword">Enum Arguments</a> instead.</p>\n<p>Deprecated keywords are shown with a strike-through in the keyword list.</p>',
      shortdoc: "*DEPRECATED* Use [Enum Arguments] instead.",
      args: [
        {
          name: "url",
          doc: "<p>a plain string.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "url: str",
        },
        {
          name: "",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "NAMED_ONLY_MARKER",
          required: false,
          repr: "*",
        },
        {
          name: "headless",
          doc: "<p>a named-only boolean.</p>",
          type: {
            name: "bool",
            typedoc: "boolean",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "True",
          kind: "NAMED_ONLY",
          required: false,
          repr: "headless: bool = True",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["deprecation"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 525,
      deprecated: true,
    },
    {
      name: "Enum Arguments",
      doc: "<p>Takes an enum, an alias of an enum, and an alias of a standard type.</p>\n<p>The enum members have string values, so no value is shown next to the\nname. Tags are rendered as well.</p>",
      shortdoc:
        "Takes an enum, an alias of an enum, and an alias of a standard type.",
      args: [
        {
          name: "selector",
          doc: "<p>uses a type alias of a standard type.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: "Locator",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selector: Locator",
        },
        {
          name: "button",
          doc: "<p>uses an enum.</p>",
          type: {
            name: "MouseButton",
            typedoc: "MouseButton",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "left",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "button: MouseButton = left",
        },
        {
          name: "",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "NAMED_ONLY_MARKER",
          required: false,
          repr: "*",
        },
        {
          name: "modifiers",
          doc: "<p>uses an alias of an enum.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "KeyboardModifier",
                typedoc: "KeyboardModifier",
                nested: [],
                union: false,
                alias: "Modifier",
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "None",
          kind: "NAMED_ONLY",
          required: false,
          repr: "modifiers: Modifier | None = None",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["arguments", "enums"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 217,
    },
    {
      name: "Enum With Integer Values",
      doc: '<p>Takes and returns an enum whose members have integer values.</p>\n<p>The values are shown next to the names, unlike the string-valued enum in\n<a href="#Enum%20Arguments" title="&quot;Enum Arguments&quot; keyword">Enum Arguments</a>.</p>',
      shortdoc: "Takes and returns an enum whose members have integer values.",
      args: [
        {
          name: "level",
          doc: "<p>uses an enum with integer values.</p>",
          type: {
            name: "LogLevel",
            typedoc: "LogLevel",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "INFO",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "level: LogLevel = INFO",
        },
      ],
      returnType: {
        name: "LogLevel",
        typedoc: "LogLevel",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The previous level.</p>",
      raises: {},
      tags: ["enums"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 328,
    },
    {
      name: "Literal With Mixed Types",
      doc: "<p>Takes a literal whose members are not all of the same type.</p>",
      shortdoc: "Takes a literal whose members are not all of the same type.",
      args: [
        {
          name: "strategy",
          doc: "<p>uses a literal with mixed member types.</p>",
          type: {
            name: "Literal",
            typedoc: "Literal",
            nested: [
              {
                name: "'css'",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "'xpath'",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "'text'",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "1",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "True",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "strategy: Literal['css', 'xpath', 'text', 1, True]",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["literals"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 345,
    },
    {
      name: "Long Argument Documentation",
      doc: "<p>Documents one argument at length, with code blocks inside it.</p>",
      shortdoc: "Documents one argument at length, with code blocks inside it.",
      args: [
        {
          name: "session",
          doc: '<p>session to attach to. Must be a session id returned by\nanother keyword, or the name of a session stored in the\n<code>sessions</code> mapping of the library.</p>\n<p>A session id can be read from Python, which is how another\nlibrary hands one over:</p>\n<div class="code"><pre><span></span><code><span class="kn">from</span><span class="w"> </span><span class="nn">robot.libraries.BuiltIn</span><span class="w"> </span><span class="kn">import</span> <span class="n">BuiltIn</span>\n\n<span class="k">def</span><span class="w"> </span><span class="nf">get_browser_session</span><span class="p">():</span>\n    <span class="n">library</span> <span class="o">=</span> <span class="n">BuiltIn</span><span class="p">()</span><span class="o">.</span><span class="n">get_library_instance</span><span class="p">(</span><span class="s2">"DevLibrary"</span><span class="p">)</span>\n    <span class="k">return</span> <span class="n">library</span><span class="o">.</span><span class="n">sessions</span><span class="o">.</span><span class="n">current</span>\n</code></pre></div>\n\n<p>The id is then given to this keyword in a test:</p>\n<div class="code"><pre><span></span><code><span class="gh">*** Settings ***</span>\n<span class="kn">Library</span><span class="p">    </span><span class="nn">DevLibrary</span>\n<span class="kn">Library</span><span class="p">    ${</span><span class="nv">CURDIR</span><span class="p">}</span><span class="nn">/browser_session.py</span>\n\n<span class="gh">*** Test Cases ***</span>\n<span class="gu">Example</span>\n<span class="p">    ${</span><span class="nv">session</span><span class="p">} =    </span><span class="nf">Get Browser Session</span>\n<span class="p">    </span><span class="nf">Long Argument Documentation</span><span class="p">    ${</span><span class="nv">session</span><span class="p">}</span>\n</code></pre></div>\n\n<p>Leaving the argument empty attaches to the session that was\nused last.</p>',
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "session: str = ",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["arguments"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 374,
    },
    {
      name: "Nested Generic Type",
      doc: "<p>Takes and returns a generic type nested inside another.</p>",
      shortdoc: "Takes and returns a generic type nested inside another.",
      args: [
        {
          name: "options",
          doc: "<p>uses a nested generic type.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "dict",
                typedoc: "dictionary",
                nested: [
                  {
                    name: "str",
                    typedoc: "string",
                    nested: [],
                    union: false,
                    alias: null,
                  },
                  {
                    name: "list",
                    typedoc: "list",
                    nested: [
                      {
                        name: "int",
                        typedoc: "integer",
                        nested: [],
                        union: false,
                        alias: null,
                      },
                    ],
                    union: false,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "options: dict[str, list[int]] | None = None",
        },
      ],
      returnType: {
        name: "dict",
        typedoc: "dictionary",
        nested: [
          {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "list",
            typedoc: "list",
            nested: [
              {
                name: "int",
                typedoc: "integer",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: false,
            alias: null,
          },
        ],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The previous options.</p>",
      raises: {},
      tags: ["generics"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 470,
    },
    {
      name: "No Arguments",
      doc: "<p>Takes no arguments at all, so no argument table is rendered.</p>",
      shortdoc: "Takes no arguments at all, so no argument table is rendered.",
      args: [],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["arguments"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 507,
    },
    {
      name: "Parameterized Alias",
      doc: "<p>Takes and returns a parameterized alias, with different parameters.</p>",
      shortdoc:
        "Takes and returns a parameterized alias, with different parameters.",
      args: [
        {
          name: "value",
          doc: "<p>uses a parameterized alias.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: "Boxed[str]",
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "value: Boxed[str] = None",
        },
      ],
      returnType: {
        name: "Union",
        typedoc: null,
        nested: [
          {
            name: "int",
            typedoc: "integer",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "None",
            typedoc: "None",
            nested: [],
            union: false,
            alias: null,
          },
        ],
        union: true,
        alias: "Boxed[int]",
      },
      returnDoc:
        "<p>The boxed value, using the same alias with other parameters.</p>",
      raises: {},
      tags: ["aliases"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 413,
    },
    {
      name: "Recursive Alias",
      doc: "<p>Takes and returns an alias that refers to itself.</p>",
      shortdoc: "Takes and returns an alias that refers to itself.",
      args: [
        {
          name: "data",
          doc: "<p>uses a recursive alias.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "int",
                typedoc: "integer",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "list",
                typedoc: "list",
                nested: [
                  {
                    name: "Json",
                    typedoc: null,
                    nested: [],
                    union: false,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: "Json",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "data: Json",
        },
      ],
      returnType: {
        name: "Union",
        typedoc: null,
        nested: [
          {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "int",
            typedoc: "integer",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "list",
            typedoc: "list",
            nested: [
              {
                name: "Json",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: false,
            alias: null,
          },
        ],
        union: true,
        alias: "Json",
      },
      returnDoc: "<p>The evaluated data.</p>",
      raises: {},
      tags: ["aliases"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 427,
    },
    {
      name: "Returns And Raises",
      doc: '<p>Documents a return value and two exceptions.</p>\n<p>The <code>selector</code> argument uses the same alias as <a href="#Enum%20Arguments" title="&quot;Enum Arguments&quot; keyword">Enum Arguments</a>, so the\nalias is used by more than one keyword.</p>',
      shortdoc: "Documents a return value and two exceptions.",
      args: [
        {
          name: "selector",
          doc: "<p>element to read.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: "Locator",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selector: Locator",
        },
      ],
      returnType: {
        name: "str",
        typedoc: "string",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>Text of the element.</p>",
      raises: {
        ValueError: "<p>if the element does not exist.</p>",
        TypeError: "<p>if the selector is not a string.</p>",
      },
      tags: ["returns"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 238,
    },
    {
      name: "TypedDict Argument And Return",
      doc: '<p>Takes and returns a TypedDict directly, without an alias.</p>\n<p>The name is set with <code>@keyword</code>, as in <a href="#Alias%20Of%20TypedDict" title="&quot;Alias Of TypedDict&quot; keyword">Alias Of TypedDict</a>.</p>',
      shortdoc: "Takes and returns a TypedDict directly, without an alias.",
      args: [
        {
          name: "size",
          doc: "<p>uses a TypedDict directly.</p>",
          type: {
            name: "ViewportSize",
            typedoc: "ViewportSize",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "size: ViewportSize",
        },
      ],
      returnType: {
        name: "ViewportSize",
        typedoc: "ViewportSize",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The previous size, using the same TypedDict.</p>",
      raises: {},
      tags: ["typeddicts"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 312,
    },
  ],
  typedocs: [
    {
      type: "Standard",
      name: "boolean",
      doc: '<p>Strings <code>TRUE</code>, <code>YES</code>, <code>ON</code>, <code>1</code> and possible localization specific "true strings"\nare converted to Boolean <code>True</code>, the empty string, strings <code>FALSE</code>, <code>NO</code>, <code>OFF</code>\nand <code>0</code> and possibly localization specific "false strings" are converted to\nBoolean <code>False</code>, and the string <code>NONE</code> is converted to the Python <code>None</code> object.\nOther strings and all other values are passed as-is, allowing keywords to handle\nthem specially if needed.</p>\n<p>All string comparisons are case-insensitive.</p>\n<p>Examples: <code>TRUE</code> (converted to <code>True</code>), <code>off</code> (converted to <code>False</code>), <code>example</code>\n(used as-is)</p>',
      usages: ["Deeply Nested Aliases", "Deprecated Keyword"],
      accepts: ["string", "integer", "float", "None"],
    },
    {
      type: "Custom",
      name: "Credential",
      doc: "<p>Username and password, given as <code>user:password</code>.</p>\n<p>The class itself is the converter, so this documentation is used.</p>",
      usages: ["Custom Type Documented By Class"],
      accepts: [],
    },
    {
      type: "Standard",
      name: "dictionary",
      doc: "<p>Strings must be Python <a href=\"https://docs.python.org/library/stdtypes.html#dict\">dictionary</a> literals. They are converted to actual\ndictionaries using the <a href=\"https://docs.python.org/library/stdtypes.html#ast.literal_eval\">ast.literal_eval</a> function. They can contain any values\n<code>ast.literal_eval</code> supports, including dictionaries and other collections.</p>\n<p>Any mapping is accepted and converted to a <code>dict</code>.</p>\n<p>If the type has nested types like <code>dict[str, int]</code>, items are converted to those\ntypes automatically. This in new in Robot Framework 6.0.</p>\n<p>Examples: <code>{'a': 1, 'b': 2}</code>, <code>{'key': 1, 'nested': {'key': 2}}</code></p>",
      usages: ["__init__", "Nested Generic Type"],
      accepts: ["string", "Mapping"],
    },
    {
      type: "Standard",
      name: "float",
      doc: '<p>Conversion is done using Python\'s <a href="https://docs.python.org/library/functions.html#float">float</a> built-in function.</p>\n<p>Spaces and underscores can be used as visual separators for digit grouping purposes.</p>\n<p>Examples: <code>3.14</code>, <code>2.9979e8</code>, <code>10 000.000 01</code></p>',
      usages: ["Alias Of TypedDict"],
      accepts: ["string", "Real"],
    },
    {
      type: "Standard",
      name: "integer",
      doc: '<p>Conversion is done using Python\'s <a href="https://docs.python.org/library/functions.html#int">int</a> built-in function. Floating point numbers\nare accepted only if they can be represented as integers exactly. For example,\n<code>1.0</code> is accepted but <code>1.1</code> is not.</p>\n<p>It is possible to use hexadecimal, octal and binary numbers by prefixing values\nwith <code>0x</code>, <code>0o</code> and <code>0b</code>, respectively.</p>\n<p>Spaces and underscores can be used as visual separators for digit grouping purposes.</p>\n<p>Examples: <code>42</code>, <code>-1</code>, <code>0b1010</code>, <code>10 000 000</code>, <code>0xBAD_C0FFEE</code></p>',
      usages: [
        "Alias Inside Generic Type",
        "Nested Generic Type",
        "Parameterized Alias",
        "Recursive Alias",
      ],
      accepts: ["string", "float"],
    },
    {
      type: "Enum",
      name: "KeyboardModifier",
      doc: "<p>Modifier keys to press while doing other actions.</p>",
      usages: ["Enum Arguments"],
      accepts: ["string"],
      members: [
        { name: "Alt", value: "Alt" },
        { name: "Control", value: "Control" },
        { name: "Meta", value: "Meta" },
        { name: "Shift", value: "Shift" },
      ],
    },
    {
      type: "Standard",
      name: "list",
      doc: "<p>Strings must be Python <a href=\"https://docs.python.org/library/stdtypes.html#list\">list</a> or <a href=\"https://docs.python.org/library/stdtypes.html#tuple\">tuple</a> literals. They are converted using the\n<a href=\"https://docs.python.org/library/stdtypes.html#ast.literal_eval\">ast.literal_eval</a> function and possible tuples are converted further to lists.\nThey can contain any values <code>ast.literal_eval</code> supports, including lists and\nother collections.</p>\n<p>If the argument is a list, it is used without conversion. Tuples and other\nsequences are converted to lists.</p>\n<p>If the type has nested types like <code>list[int]</code>, items are converted to those\ntypes automatically.</p>\n<p>Examples: <code>['one', 'two']</code>, <code>[('one', 1), ('two', 2)]</code></p>\n<p>Support to convert nested types is new in Robot Framework 6.0. Support for tuple\nliterals is new in Robot Framework 7.4.</p>",
      usages: [
        "Alias Inside Generic Type",
        "Deeply Nested Aliases",
        "Nested Generic Type",
        "Recursive Alias",
      ],
      accepts: ["string", "Sequence"],
    },
    {
      type: "Standard",
      name: "Literal",
      doc: "<p>Only specified values are accepted. Values can be strings, integers, bytes,\nBooleans, enums and None, and used arguments are converted using the value type\nspecific conversion logic.</p>\n<p>String matching is case, space, underscore and hyphen insensitive, but exact\nmatches have precedence over normalized matches.</p>",
      usages: ["Literal With Mixed Types"],
      accepts: ["Any"],
    },
    {
      type: "Enum",
      name: "LogLevel",
      doc: "<p>Severity of a log message.</p>\n<p>Members have integer values, which are shown next to the names.</p>",
      usages: ["Enum With Integer Values"],
      accepts: ["string", "integer"],
      members: [
        { name: "TRACE", value: "0" },
        { name: "DEBUG", value: "10" },
        { name: "INFO", value: "20" },
        { name: "WARN", value: "30" },
      ],
    },
    {
      type: "Enum",
      name: "MouseButton",
      doc: "<p>Mouse button to click with.</p>\n<p>Members have string values, so no value is shown next to the name.</p>",
      usages: ["__init__", "Enum Arguments"],
      accepts: ["string"],
      members: [
        { name: "left", value: "left" },
        { name: "middle", value: "middle" },
        { name: "right", value: "right" },
      ],
    },
    {
      type: "Standard",
      name: "None",
      doc: "<p>String <code>NONE</code> (case-insensitive) and the empty string are converted to the Python\n<code>None</code> object. Other values cause an error.</p>\n<p>Converting the empty string is new in Robot Framework 7.4.</p>",
      usages: [
        "__init__",
        "Alias Of None",
        "Alias Of Union",
        "Enum Arguments",
        "Nested Generic Type",
        "Parameterized Alias",
      ],
      accepts: ["string"],
    },
    {
      type: "TypedDict",
      name: "PdfMargins",
      doc: "<p>Margins of the generated PDF.</p>\n<p>Only <code>top</code> and <code>bottom</code> are required. The optional keys are declared by a\n<code>total=False</code> subclass, because <code>NotRequired</code> would leak into the rendered\nkey type.</p>",
      usages: ["Alias Of TypedDict"],
      accepts: ["string", "Mapping"],
      items: [
        { key: "top", type: "str", required: true },
        { key: "bottom", type: "str", required: true },
        { key: "left", type: "str", required: false },
        { key: "right", type: "str", required: false },
      ],
    },
    {
      type: "Custom",
      name: "SelectorSpec",
      doc: "<p>Selector in the <code>strategy=value</code> format, for example <code>id=submit</code>.</p>",
      usages: ["Custom Type With Converter Method", "Deeply Nested Aliases"],
      accepts: ["string", "integer"],
    },
    {
      type: "Standard",
      name: "string",
      doc: '<p>All arguments are converted to Unicode strings.</p>\n<p>Most values are converted simply by using <code>str(value)</code>. An exception is that\nbytes are mapped directly to Unicode code points with same ordinals. This means\nthat, for example, <code>b"hyv\\xe4"</code> becomes <code>"hyvä"</code>.</p>\n<p>Converting bytes specially is new Robot Framework 7.4.</p>',
      usages: [
        "__init__",
        "Alias Inside Generic Type",
        "Alias Of TypedDict",
        "Alias Of Union",
        "Deeply Nested Aliases",
        "Deprecated Keyword",
        "Enum Arguments",
        "Long Argument Documentation",
        "Nested Generic Type",
        "Parameterized Alias",
        "Recursive Alias",
        "Returns And Raises",
      ],
      accepts: ["Any"],
    },
    {
      type: "Standard",
      name: "timedelta",
      doc: '<p>Strings are expected to represent a time interval in one of the time formats\nRobot Framework supports:</p>\n<ul>\n<li>a number representing seconds like <code>42</code> or <code>10.5</code></li>\n<li>a "time string" like <code>1 hour 2 seconds</code> or <code>1h 2s</code></li>\n<li>a "timer string" like <code>01:02</code> (1 minute 2 seconds) or <code>01:00:03</code> (1 hour 3 seconds)</li>\n</ul>\n<p>Integers and floats are considered to be seconds.</p>\n<p>See the <a href="https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#time-format">User Guide</a> for more details about the supported time formats.</p>',
      usages: ["__init__", "Alias Inside Generic Type"],
      accepts: ["string", "integer", "float"],
    },
    {
      type: "TypedDict",
      name: "ViewportSize",
      doc: "<p>Size of the browser viewport in pixels.</p>",
      usages: ["TypedDict Argument And Return"],
      accepts: ["string", "Mapping"],
      items: [
        { key: "width", type: "int", required: true },
        { key: "height", type: "int", required: true },
      ],
    },
  ],
};

export { DATA };
