// Development fixture rendered by `npm start`, generated with Libdoc from
// libdoc/DevLibrary.py. Add a case to the UI by adding a keyword there.
//
// Do not edit by hand: run `npm run testdata`, or just save DevLibrary.py
// while `npm start` is running.
import type { Libdoc } from "./types";

const DATA: Libdoc = {
  specversion: 4,
  name: "DevLibrary",
  doc: '<p>Library for developing the Libdoc HTML frontend.</p>\n<div class="toc">\n<ul>\n<li><a href="#purpose">Purpose</a></li>\n<li><a href="#what-is-covered">What is covered</a></li>\n<li><a href="#formatting-examples">Formatting examples</a><ul>\n<li><a href="#lists">Lists</a></li>\n<li><a href="#code-blocks">Code blocks</a></li>\n</ul>\n</li>\n</ul>\n</div>\n<h2 id="purpose">Purpose</h2>\n<p>This library exists only to produce the development fixture rendered by\n<code>npm start</code>. It is not shipped and it is not used by any test. Every keyword\nhere earns its place by exercising something the frontend renders, so adding a\nkeyword is how you add a case to the fixture.</p>\n<p>Run <code>npm run testdata</code> to regenerate <code>testdata.ts</code> from this file. The dev\nserver does it for you whenever this file is saved.</p>\n<h2 id="what-is-covered">What is covered</h2>\n<table>\n<thead>\n<tr>\n<th>Type</th>\n<th>Where to look</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Type aliases</td>\n<td><a href="#Click" title="&quot;Click&quot; keyword">Click</a>, <a href="#Connect%20To%20Browser" title="&quot;Connect To Browser&quot; keyword">Connect To Browser</a>, <a href="#Evaluate%20Json" title="&quot;Evaluate Json&quot; keyword">Evaluate Json</a>, <a href="#Box%20Value" title="&quot;Box Value&quot; keyword">Box Value</a>,</td>\n</tr>\n<tr>\n<td><a href="#Close%20All%20Browsers" title="&quot;Close All Browsers&quot; keyword">Close All Browsers</a></td>\n<td></td>\n</tr>\n<tr>\n<td>Nested type aliases</td>\n<td><a href="#Scroll%20To%20Element" title="&quot;Scroll To Element&quot; keyword">Scroll To Element</a></td>\n</tr>\n<tr>\n<td>Long argument documentation</td>\n<td><a href="#Attach%20To%20Session" title="&quot;Attach To Session&quot; keyword">Attach To Session</a></td>\n</tr>\n<tr>\n<td>Enums</td>\n<td><a href="#Click" title="&quot;Click&quot; keyword">Click</a>, <a href="#Set%20Log%20Level" title="&quot;Set Log Level&quot; keyword">Set Log Level</a></td>\n</tr>\n<tr>\n<td>TypedDicts</td>\n<td><a href="#Save%20Page%20As%20Pdf" title="&quot;Save Page As Pdf&quot; keyword">Save Page As Pdf</a>, <a href="#Set%20Viewport%20Size" title="&quot;Set Viewport Size&quot; keyword">Set Viewport Size</a></td>\n</tr>\n<tr>\n<td>Custom types</td>\n<td><a href="#Parse%20Selector" title="&quot;Parse Selector&quot; keyword">Parse Selector</a>, <a href="#Set%20Credentials" title="&quot;Set Credentials&quot; keyword">Set Credentials</a></td>\n</tr>\n<tr>\n<td>Argument kinds</td>\n<td><a href="#All%20Argument%20Kinds" title="&quot;All Argument Kinds&quot; keyword">All Argument Kinds</a></td>\n</tr>\n</tbody>\n</table>\n<div class="admonition note">\n<p class="admonition-title">Note</p>\n<p>Documentation is written in Markdown, so this text also covers the Markdown\nfeatures the frontend has to render.</p>\n</div>\n<div class="admonition tip">\n<p class="admonition-title">Admonitions have optional titles</p>\n<p>And they nest:</p>\n<div class="admonition warning">\n<p class="admonition-title">Warning</p>\n<p>Do not add cases here that a real library could not produce.</p>\n</div>\n</div>\n<h2 id="formatting-examples">Formatting examples</h2>\n<p>Basic formatting such as <strong>bold</strong>, <em>italics</em> and <code>code</code> works, and so do links\nto keywords like <a href="#Get%20Text" title="&quot;Get Text&quot; keyword">Get Text</a>, to types like <a href="#type-integer" title="&quot;integer&quot; type">int</a> and to sections like\n<a href="#purpose" title="&quot;Purpose&quot; section">Purpose</a>.</p>\n<h3 id="lists">Lists</h3>\n<ul>\n<li>Unordered item.<ul>\n<li>Nested item.</li>\n<li>Another nested item.</li>\n</ul>\n</li>\n<li>Item with an ordered sublist.<ol>\n<li>First.</li>\n<li>Second.</li>\n</ol>\n</li>\n</ul>\n<h3 id="code-blocks">Code blocks</h3>\n<div class="code"><pre><span></span><code><span class="gh">*** Test Cases ***</span>\n<span class="gu">Example</span>\n<span class="p">    </span><span class="nf">Click</span><span class="p">    </span><span class="s">id=submit</span><span class="p">    </span><span class="s">button=right</span>\n</code></pre></div>',
  version: "1.2.3",
  generated: "2024-01-01T00:00:00+00:00",
  type: "LIBRARY",
  scope: "GLOBAL",
  docFormat: "HTML",
  source: "src/web/libdoc/DevLibrary.py",
  lineno: 126,
  tags: ["action", "getter", "mouse", "setter"],
  inits: [
    {
      name: "__init__",
      doc: "<p>Configures the library when it is imported.</p>",
      shortdoc: "Configures the library when it is imported.",
      args: [
        {
          name: "browser",
          doc: "<p>browser to open.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "MouseButton",
                typedoc: "MouseButton",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "chromium",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "browser: MouseButton | str = chromium",
        },
        {
          name: "timeout",
          doc: "<p>default timeout for keywords that wait.</p>",
          type: {
            name: "timedelta",
            typedoc: "timedelta",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "0:00:10",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "timeout: timedelta = 0:00:10",
        },
        {
          name: "options",
          doc: "<p>extra options passed to the browser.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "dict",
                typedoc: "dictionary",
                nested: [
                  {
                    name: "str",
                    typedoc: "string",
                    nested: [],
                    union: false,
                    alias: null,
                  },
                  {
                    name: "str",
                    typedoc: "string",
                    nested: [],
                    union: false,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "options: dict[str, str] | None = None",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 188,
    },
  ],
  keywords: [
    {
      name: "All Argument Kinds",
      doc: "<p>Has every kind of argument there is.</p>",
      shortdoc: "Has every kind of argument there is.",
      args: [
        {
          name: "a",
          doc: "<p>positional-only argument.</p>",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_ONLY",
          required: true,
          repr: "a",
        },
        {
          name: "",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_ONLY_MARKER",
          required: false,
          repr: "/",
        },
        {
          name: "b",
          doc: "<p>normal argument, whose documentation\ncontinues on the next line.</p>",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "b",
        },
        {
          name: "c",
          doc: "<p>normal argument with a default value.</p>",
          type: null,
          defaultValue: "d",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "c=d",
        },
        {
          name: "e",
          doc: "<p>free positional arguments.</p>",
          type: null,
          defaultValue: null,
          kind: "VAR_POSITIONAL",
          required: false,
          repr: "*e",
        },
        {
          name: "f",
          doc: "<p>named-only argument without a default value.</p>",
          type: null,
          defaultValue: null,
          kind: "NAMED_ONLY",
          required: true,
          repr: "f",
        },
        {
          name: "g",
          doc: "<p>named-only argument with a default value.</p>",
          type: null,
          defaultValue: "h",
          kind: "NAMED_ONLY",
          required: false,
          repr: "g=h",
        },
        {
          name: "i",
          doc: "<p>free named arguments.</p>",
          type: null,
          defaultValue: null,
          kind: "VAR_NAMED",
          required: false,
          repr: "**i",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 443,
    },
    {
      name: "Attach To Session",
      doc: "<p>Attaches to an already running browser session.</p>",
      shortdoc: "Attaches to an already running browser session.",
      args: [
        {
          name: "session",
          doc: '<p>session to attach to. Must be a session id returned by\n<a href="#Connect%20To%20Browser" title="&quot;Connect To Browser&quot; keyword">Connect To Browser</a>, or the name of a session stored in the\n<code>sessions</code> mapping of the library.</p>\n<p>A session id can be read from Python, which is how another\nlibrary hands one over:</p>\n<div class="code"><pre><span></span><code><span class="kn">from</span><span class="w"> </span><span class="nn">robot.libraries.BuiltIn</span><span class="w"> </span><span class="kn">import</span> <span class="n">BuiltIn</span>\n\n<span class="k">def</span><span class="w"> </span><span class="nf">get_browser_session</span><span class="p">():</span>\n    <span class="n">library</span> <span class="o">=</span> <span class="n">BuiltIn</span><span class="p">()</span><span class="o">.</span><span class="n">get_library_instance</span><span class="p">(</span><span class="s2">"DevLibrary"</span><span class="p">)</span>\n    <span class="k">return</span> <span class="n">library</span><span class="o">.</span><span class="n">sessions</span><span class="o">.</span><span class="n">current</span>\n</code></pre></div>\n\n<p>The id is then given to this keyword in a test:</p>\n<div class="code"><pre><span></span><code><span class="gh">*** Settings ***</span>\n<span class="kn">Library</span><span class="p">    </span><span class="nn">DevLibrary</span>\n<span class="kn">Library</span><span class="p">    ${</span><span class="nv">CURDIR</span><span class="p">}</span><span class="nn">/browser_session.py</span>\n\n<span class="gh">*** Test Cases ***</span>\n<span class="gu">Example</span>\n<span class="p">    ${</span><span class="nv">session</span><span class="p">} =    </span><span class="nf">Get Browser Session</span>\n<span class="p">    </span><span class="nf">Attach To Session</span><span class="p">    ${</span><span class="nv">session</span><span class="p">}</span>\n</code></pre></div>\n\n<p>Leaving the argument empty attaches to the session that was\nused last.</p>',
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "session: str = ",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 342,
    },
    {
      name: "Box Value",
      doc: "<p>Boxes a value.</p>",
      shortdoc: "Boxes a value.",
      args: [
        {
          name: "value",
          doc: "<p>value to box. Uses a parameterized alias.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: "Boxed[str]",
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "value: Boxed[str] = None",
        },
      ],
      returnType: {
        name: "Union",
        typedoc: null,
        nested: [
          {
            name: "int",
            typedoc: "integer",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "None",
            typedoc: "None",
            nested: [],
            union: false,
            alias: null,
          },
        ],
        union: true,
        alias: "Boxed[int]",
      },
      returnDoc:
        "<p>The boxed value, using the same alias with other parameters.</p>",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 381,
    },
    {
      name: "Click",
      doc: "<p>Clicks the element matching <code>selector</code>.</p>",
      shortdoc: "Clicks the element matching `selector`.",
      args: [
        {
          name: "selector",
          doc: "<p>element to click. Uses a type alias of a standard type.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: "Locator",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selector: Locator",
        },
        {
          name: "button",
          doc: "<p>which mouse button to use. Uses an enum.</p>",
          type: {
            name: "MouseButton",
            typedoc: "MouseButton",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "left",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "button: MouseButton = left",
        },
        {
          name: "",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "NAMED_ONLY_MARKER",
          required: false,
          repr: "*",
        },
        {
          name: "modifiers",
          doc: "<p>modifier key to hold down. Uses an alias of an enum.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "KeyboardModifier",
                typedoc: "KeyboardModifier",
                nested: [],
                union: false,
                alias: "Modifier",
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "None",
          kind: "NAMED_ONLY",
          required: false,
          repr: "modifiers: Modifier | None = None",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["action", "mouse"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 202,
    },
    {
      name: "Close All Browsers",
      doc: "<p>Closes every browser.</p>\n<p>Returns an alias of <code>None</code>. A keyword returning plain <code>None</code> shows no\nreturn type at all, because every Python function returns <code>None</code>\nimplicitly, but this alias was declared and annotated on purpose.</p>",
      shortdoc: "Closes every browser.",
      args: [],
      returnType: {
        name: "None",
        typedoc: "None",
        nested: [],
        union: false,
        alias: "Nothing",
      },
      returnDoc: "",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 466,
    },
    {
      name: "Close Browser",
      doc: "<p>Closes the current browser.</p>\n<p>Takes no arguments at all.</p>",
      shortdoc: "Closes the current browser.",
      args: [],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 457,
    },
    {
      name: "Connect To Browser",
      doc: "<p>Connects to an already running browser.</p>",
      shortdoc: "Connects to an already running browser.",
      args: [
        {
          name: "handle",
          doc: "<p>browser to connect to. Uses an alias of a union, which has\nno single type to document.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "Popen",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: "Handle",
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "handle: Handle = None",
        },
      ],
      returnType: {
        name: "Union",
        typedoc: null,
        nested: [
          {
            name: "Popen",
            typedoc: null,
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "None",
            typedoc: "None",
            nested: [],
            union: false,
            alias: null,
          },
        ],
        union: true,
        alias: "Handle",
      },
      returnDoc: "<p>The previous handle.</p>",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 327,
    },
    {
      name: "Evaluate Json",
      doc: "<p>Evaluates JSON data.</p>",
      shortdoc: "Evaluates JSON data.",
      args: [
        {
          name: "data",
          doc: "<p>data to evaluate. Uses a recursive alias.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "int",
                typedoc: "integer",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "list",
                typedoc: "list",
                nested: [
                  {
                    name: "Json",
                    typedoc: null,
                    nested: [],
                    union: false,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: "Json",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "data: Json",
        },
      ],
      returnType: {
        name: "Union",
        typedoc: null,
        nested: [
          {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "int",
            typedoc: "integer",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "list",
            typedoc: "list",
            nested: [
              {
                name: "Json",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: false,
            alias: null,
          },
        ],
        union: true,
        alias: "Json",
      },
      returnDoc: "<p>The evaluated data.</p>",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 392,
    },
    {
      name: "Get Text",
      doc: '<p>Returns the text of the element matching <code>selector</code>.</p>\n<p>The <code>selector</code> argument uses the same alias as <a href="#Click" title="&quot;Click&quot; keyword">Click</a>, so the alias is\nused by more than one keyword.</p>',
      shortdoc: "Returns the text of the element matching `selector`.",
      args: [
        {
          name: "selector",
          doc: "<p>element to read.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: "Locator",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selector: Locator",
        },
      ],
      returnType: {
        name: "str",
        typedoc: "string",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>Text of the element.</p>",
      raises: {
        ValueError: "<p>if the element does not exist.</p>",
        TypeError: "<p>if the selector is not a string.</p>",
      },
      tags: ["getter"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 220,
    },
    {
      name: "Highlight Elements",
      doc: "<p>Highlights all elements matching the given selectors.</p>",
      shortdoc: "Highlights all elements matching the given selectors.",
      args: [
        {
          name: "selectors",
          doc: "<p>elements to highlight. The alias is nested inside a\ngeneric type.</p>",
          type: {
            name: "list",
            typedoc: "list",
            nested: [
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: "Locator",
              },
            ],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selectors: list[Locator]",
        },
        {
          name: "duration",
          doc: "<p>how long the highlight is shown.</p>",
          type: {
            name: "timedelta",
            typedoc: "timedelta",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "0:00:02",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "duration: timedelta = 0:00:02",
        },
      ],
      returnType: {
        name: "int",
        typedoc: "integer",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>How many elements were highlighted.</p>",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 241,
    },
    {
      name: "Open Browser In Headless Mode",
      doc: '<p><em>DEPRECATED</em> Use <a href="#Click" title="&quot;Click&quot; keyword">Click</a> instead.</p>\n<p>Deprecated keywords are shown with a strike-through in the keyword list.</p>',
      shortdoc: "*DEPRECATED* Use [Click] instead.",
      args: [
        {
          name: "url",
          doc: "<p>address to open.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "url: str",
        },
        {
          name: "",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "NAMED_ONLY_MARKER",
          required: false,
          repr: "*",
        },
        {
          name: "headless",
          doc: "<p>whether to hide the browser window.</p>",
          type: {
            name: "bool",
            typedoc: "boolean",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "True",
          kind: "NAMED_ONLY",
          required: false,
          repr: "headless: bool = True",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 477,
      deprecated: true,
    },
    {
      name: "Parse Selector",
      doc: "<p>Parses a selector.</p>",
      shortdoc: "Parses a selector.",
      args: [
        {
          name: "selector",
          doc: "<p>selector to parse. Uses a custom type whose converter\nmethod is documented.</p>",
          type: {
            name: "SelectorSpec",
            typedoc: "SelectorSpec",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "selector: SelectorSpec",
        },
      ],
      returnType: {
        name: "SelectorSpec",
        typedoc: "SelectorSpec",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The parsed selector.</p>",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 403,
    },
    {
      name: "Save Page As Pdf",
      doc: "<p>Saves the current page as a PDF file.</p>",
      shortdoc: "Saves the current page as a PDF file.",
      args: [
        {
          name: "path",
          doc: "<p>where the PDF is written.</p>",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "path: str",
        },
        {
          name: "margins",
          doc: "<p>page margins. Uses an alias of a TypedDict.</p>",
          type: {
            name: "PdfMargins",
            typedoc: "PdfMargins",
            nested: [],
            union: false,
            alias: "Margins",
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "margins: Margins",
        },
        {
          name: "scale",
          doc: "<p>scale of the rendered page.</p>",
          type: {
            name: "float",
            typedoc: "float",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "1.0",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "scale: float = 1.0",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 277,
    },
    {
      name: "Scroll To Element",
      doc: "<p>Scrolls to the given element.</p>",
      shortdoc: "Scrolls to the given element.",
      args: [
        {
          name: "target",
          doc: "<p>element to scroll to. Aliases nested inside other types and\ninside each other, which is the deepest type the UI renders.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "SelectorSpec",
                typedoc: "SelectorSpec",
                nested: [],
                union: false,
                alias: "WebElement",
              },
              {
                name: "str",
                typedoc: "string",
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "list",
                typedoc: "list",
                nested: [
                  {
                    name: "Union",
                    typedoc: null,
                    nested: [
                      {
                        name: "SelectorSpec",
                        typedoc: "SelectorSpec",
                        nested: [],
                        union: false,
                        alias: "WebElement",
                      },
                      {
                        name: "str",
                        typedoc: "string",
                        nested: [],
                        union: false,
                        alias: null,
                      },
                      {
                        name: "list",
                        typedoc: "list",
                        nested: [
                          {
                            name: "str",
                            typedoc: "string",
                            nested: [],
                            union: false,
                            alias: "Locator",
                          },
                        ],
                        union: false,
                        alias: null,
                      },
                    ],
                    union: true,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "target: WebElement | str | list[WebElement | str | list[Locator]]",
        },
        {
          name: "smooth",
          doc: "<p>whether the scrolling is animated.</p>",
          type: {
            name: "bool",
            typedoc: "boolean",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "True",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "smooth: bool = True",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["action"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 261,
    },
    {
      name: "Select Strategy",
      doc: "<p>Selects the strategy used to find elements.</p>",
      shortdoc: "Selects the strategy used to find elements.",
      args: [
        {
          name: "strategy",
          doc: "<p>strategy to use. Uses a literal with mixed member types.</p>",
          type: {
            name: "Literal",
            typedoc: "Literal",
            nested: [
              {
                name: "'css'",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "'xpath'",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "'text'",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "1",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
              {
                name: "True",
                typedoc: null,
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "strategy: Literal['css', 'xpath', 'text', 1, True]",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["setter"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 317,
    },
    {
      name: "Set Credentials",
      doc: "<p>Sets the credentials used with basic authentication.</p>",
      shortdoc: "Sets the credentials used with basic authentication.",
      args: [
        {
          name: "credential",
          doc: "<p>credentials to use. Uses a custom type documented by\nthe class itself.</p>",
          type: {
            name: "Credential",
            typedoc: "Credential",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "credential: Credential",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["setter"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 415,
    },
    {
      name: "Set Log Level",
      doc: "<p>Sets the log level.</p>",
      shortdoc: "Sets the log level.",
      args: [
        {
          name: "level",
          doc: "<p>new level. Uses an enum with integer values.</p>",
          type: {
            name: "LogLevel",
            typedoc: "LogLevel",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "INFO",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "level: LogLevel = INFO",
        },
      ],
      returnType: {
        name: "LogLevel",
        typedoc: "LogLevel",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The previous level.</p>",
      raises: {},
      tags: ["setter"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 303,
    },
    {
      name: "Set Options",
      doc: "<p>Sets extra options.</p>",
      shortdoc: "Sets extra options.",
      args: [
        {
          name: "options",
          doc: "<p>options to set. Uses a nested generic type.</p>",
          type: {
            name: "Union",
            typedoc: null,
            nested: [
              {
                name: "dict",
                typedoc: "dictionary",
                nested: [
                  {
                    name: "str",
                    typedoc: "string",
                    nested: [],
                    union: false,
                    alias: null,
                  },
                  {
                    name: "list",
                    typedoc: "list",
                    nested: [
                      {
                        name: "int",
                        typedoc: "integer",
                        nested: [],
                        union: false,
                        alias: null,
                      },
                    ],
                    union: false,
                    alias: null,
                  },
                ],
                union: false,
                alias: null,
              },
              {
                name: "None",
                typedoc: "None",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: true,
            alias: null,
          },
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "options: dict[str, list[int]] | None = None",
        },
      ],
      returnType: {
        name: "dict",
        typedoc: "dictionary",
        nested: [
          {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          {
            name: "list",
            typedoc: "list",
            nested: [
              {
                name: "int",
                typedoc: "integer",
                nested: [],
                union: false,
                alias: null,
              },
            ],
            union: false,
            alias: null,
          },
        ],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The previous options.</p>",
      raises: {},
      tags: ["setter"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 426,
    },
    {
      name: "Set Viewport Size",
      doc: "<p>Sets the viewport size.</p>",
      shortdoc: "Sets the viewport size.",
      args: [
        {
          name: "size",
          doc: "<p>new size. Uses a TypedDict directly.</p>",
          type: {
            name: "ViewportSize",
            typedoc: "ViewportSize",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "size: ViewportSize",
        },
      ],
      returnType: {
        name: "ViewportSize",
        typedoc: "ViewportSize",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "<p>The previous size.</p>",
      raises: {},
      tags: ["setter"],
      source: "src/web/libdoc/DevLibrary.py",
      lineno: 289,
    },
  ],
  typedocs: [
    {
      type: "Standard",
      name: "boolean",
      doc: '<p>Strings <code>TRUE</code>, <code>YES</code>, <code>ON</code>, <code>1</code> and possible localization specific "true strings"\nare converted to Boolean <code>True</code>, the empty string, strings <code>FALSE</code>, <code>NO</code>, <code>OFF</code>\nand <code>0</code> and possibly localization specific "false strings" are converted to\nBoolean <code>False</code>, and the string <code>NONE</code> is converted to the Python <code>None</code> object.\nOther strings and all other values are passed as-is, allowing keywords to handle\nthem specially if needed.</p>\n<p>All string comparisons are case-insensitive.</p>\n<p>Examples: <code>TRUE</code> (converted to <code>True</code>), <code>off</code> (converted to <code>False</code>), <code>example</code>\n(used as-is)</p>',
      usages: ["Open Browser In Headless Mode", "Scroll To Element"],
      accepts: ["string", "integer", "float", "None"],
    },
    {
      type: "Custom",
      name: "Credential",
      doc: "<p>Username and password, given as <code>user:password</code>.</p>\n<p>The class itself is the converter, so this documentation is used.</p>",
      usages: ["Set Credentials"],
      accepts: [],
    },
    {
      type: "Standard",
      name: "dictionary",
      doc: "<p>Strings must be Python <a href=\"https://docs.python.org/library/stdtypes.html#dict\">dictionary</a> literals. They are converted to actual\ndictionaries using the <a href=\"https://docs.python.org/library/stdtypes.html#ast.literal_eval\">ast.literal_eval</a> function. They can contain any values\n<code>ast.literal_eval</code> supports, including dictionaries and other collections.</p>\n<p>Any mapping is accepted and converted to a <code>dict</code>.</p>\n<p>If the type has nested types like <code>dict[str, int]</code>, items are converted to those\ntypes automatically. This in new in Robot Framework 6.0.</p>\n<p>Examples: <code>{'a': 1, 'b': 2}</code>, <code>{'key': 1, 'nested': {'key': 2}}</code></p>",
      usages: ["__init__", "Set Options"],
      accepts: ["string", "Mapping"],
    },
    {
      type: "Standard",
      name: "float",
      doc: '<p>Conversion is done using Python\'s <a href="https://docs.python.org/library/functions.html#float">float</a> built-in function.</p>\n<p>Spaces and underscores can be used as visual separators for digit grouping purposes.</p>\n<p>Examples: <code>3.14</code>, <code>2.9979e8</code>, <code>10 000.000 01</code></p>',
      usages: ["Save Page As Pdf"],
      accepts: ["string", "Real"],
    },
    {
      type: "Standard",
      name: "integer",
      doc: '<p>Conversion is done using Python\'s <a href="https://docs.python.org/library/functions.html#int">int</a> built-in function. Floating point numbers\nare accepted only if they can be represented as integers exactly. For example,\n<code>1.0</code> is accepted but <code>1.1</code> is not.</p>\n<p>It is possible to use hexadecimal, octal and binary numbers by prefixing values\nwith <code>0x</code>, <code>0o</code> and <code>0b</code>, respectively.</p>\n<p>Spaces and underscores can be used as visual separators for digit grouping purposes.</p>\n<p>Examples: <code>42</code>, <code>-1</code>, <code>0b1010</code>, <code>10 000 000</code>, <code>0xBAD_C0FFEE</code></p>',
      usages: [
        "Box Value",
        "Evaluate Json",
        "Highlight Elements",
        "Set Options",
      ],
      accepts: ["string", "float"],
    },
    {
      type: "Enum",
      name: "KeyboardModifier",
      doc: "<p>Modifier keys to press while doing other actions.</p>",
      usages: ["Click"],
      accepts: ["string"],
      members: [
        { name: "Alt", value: "Alt" },
        { name: "Control", value: "Control" },
        { name: "Meta", value: "Meta" },
        { name: "Shift", value: "Shift" },
      ],
    },
    {
      type: "Standard",
      name: "list",
      doc: "<p>Strings must be Python <a href=\"https://docs.python.org/library/stdtypes.html#list\">list</a> or <a href=\"https://docs.python.org/library/stdtypes.html#tuple\">tuple</a> literals. They are converted using the\n<a href=\"https://docs.python.org/library/stdtypes.html#ast.literal_eval\">ast.literal_eval</a> function and possible tuples are converted further to lists.\nThey can contain any values <code>ast.literal_eval</code> supports, including lists and\nother collections.</p>\n<p>If the argument is a list, it is used without conversion. Tuples and other\nsequences are converted to lists.</p>\n<p>If the type has nested types like <code>list[int]</code>, items are converted to those\ntypes automatically.</p>\n<p>Examples: <code>['one', 'two']</code>, <code>[('one', 1), ('two', 2)]</code></p>\n<p>Support to convert nested types is new in Robot Framework 6.0. Support for tuple\nliterals is new in Robot Framework 7.4.</p>",
      usages: [
        "Evaluate Json",
        "Highlight Elements",
        "Scroll To Element",
        "Set Options",
      ],
      accepts: ["string", "Sequence"],
    },
    {
      type: "Standard",
      name: "Literal",
      doc: "<p>Only specified values are accepted. Values can be strings, integers, bytes,\nBooleans, enums and None, and used arguments are converted using the value type\nspecific conversion logic.</p>\n<p>String matching is case, space, underscore and hyphen insensitive, but exact\nmatches have precedence over normalized matches.</p>",
      usages: ["Select Strategy"],
      accepts: ["Any"],
    },
    {
      type: "Enum",
      name: "LogLevel",
      doc: "<p>Severity of a log message.</p>\n<p>Members have integer values, which are shown next to the names.</p>",
      usages: ["Set Log Level"],
      accepts: ["string", "integer"],
      members: [
        { name: "TRACE", value: "0" },
        { name: "DEBUG", value: "10" },
        { name: "INFO", value: "20" },
        { name: "WARN", value: "30" },
      ],
    },
    {
      type: "Enum",
      name: "MouseButton",
      doc: "<p>Mouse button to click with.</p>\n<p>Members have string values, so no value is shown next to the name.</p>",
      usages: ["__init__", "Click"],
      accepts: ["string"],
      members: [
        { name: "left", value: "left" },
        { name: "middle", value: "middle" },
        { name: "right", value: "right" },
      ],
    },
    {
      type: "Standard",
      name: "None",
      doc: "<p>String <code>NONE</code> (case-insensitive) and the empty string are converted to the Python\n<code>None</code> object. Other values cause an error.</p>\n<p>Converting the empty string is new in Robot Framework 7.4.</p>",
      usages: [
        "__init__",
        "Box Value",
        "Click",
        "Close All Browsers",
        "Connect To Browser",
        "Set Options",
      ],
      accepts: ["string"],
    },
    {
      type: "TypedDict",
      name: "PdfMargins",
      doc: "<p>Margins of the generated PDF.</p>\n<p>Only <code>top</code> and <code>bottom</code> are required. The optional keys are declared by a\n<code>total=False</code> subclass, because <code>NotRequired</code> would leak into the rendered\nkey type.</p>",
      usages: ["Save Page As Pdf"],
      accepts: ["string", "Mapping"],
      items: [
        { key: "top", type: "str", required: true },
        { key: "bottom", type: "str", required: true },
        { key: "left", type: "str", required: false },
        { key: "right", type: "str", required: false },
      ],
    },
    {
      type: "Custom",
      name: "SelectorSpec",
      doc: "<p>Selector in the <code>strategy=value</code> format, for example <code>id=submit</code>.</p>",
      usages: ["Parse Selector", "Scroll To Element"],
      accepts: ["string", "integer"],
    },
    {
      type: "Standard",
      name: "string",
      doc: '<p>All arguments are converted to Unicode strings.</p>\n<p>Most values are converted simply by using <code>str(value)</code>. An exception is that\nbytes are mapped directly to Unicode code points with same ordinals. This means\nthat, for example, <code>b"hyv\\xe4"</code> becomes <code>"hyvä"</code>.</p>\n<p>Converting bytes specially is new Robot Framework 7.4.</p>',
      usages: [
        "__init__",
        "Attach To Session",
        "Box Value",
        "Click",
        "Connect To Browser",
        "Evaluate Json",
        "Get Text",
        "Highlight Elements",
        "Open Browser In Headless Mode",
        "Save Page As Pdf",
        "Scroll To Element",
        "Set Options",
      ],
      accepts: ["Any"],
    },
    {
      type: "Standard",
      name: "timedelta",
      doc: '<p>Strings are expected to represent a time interval in one of the time formats\nRobot Framework supports:</p>\n<ul>\n<li>a number representing seconds like <code>42</code> or <code>10.5</code></li>\n<li>a "time string" like <code>1 hour 2 seconds</code> or <code>1h 2s</code></li>\n<li>a "timer string" like <code>01:02</code> (1 minute 2 seconds) or <code>01:00:03</code> (1 hour 3 seconds)</li>\n</ul>\n<p>Integers and floats are considered to be seconds.</p>\n<p>See the <a href="https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#time-format">User Guide</a> for more details about the supported time formats.</p>',
      usages: ["__init__", "Highlight Elements"],
      accepts: ["string", "integer", "float"],
    },
    {
      type: "TypedDict",
      name: "ViewportSize",
      doc: "<p>Size of the browser viewport in pixels.</p>",
      usages: ["Set Viewport Size"],
      accepts: ["string", "Mapping"],
      items: [
        { key: "width", type: "int", required: true },
        { key: "height", type: "int", required: true },
      ],
    },
  ],
};

export { DATA };
