// Development fixture rendered by `npm start`, generated with Libdoc from
// libdoc/DevLibraryRobotFormat.py. Add a case to the UI by adding a keyword there.
//
// Do not edit by hand: run `npm run testdata`, or just save DevLibraryRobotFormat.py
// while `npm start` is running.
import type { Libdoc } from "./types";

const DATA: Libdoc = {
  specversion: 4,
  name: "DevLibraryRobotFormat",
  doc: '<p>Library for developing the Libdoc HTML frontend against the ROBOT format.</p>\n<h2 id="Purpose">Purpose</h2>\n<p>This library is the counterpart of <code>DevLibrary.py</code>, which uses Markdown. It exists for one reason: documentation tables render the same whatever format produced them, but the ROBOT format is where the awkward cases come from, and nothing else in the fixture produces them.</p>\n<p>Tables are also the one part of library documentation whose content is entirely up to the library author, so the styling has to survive shapes the frontend never chose. Every keyword here documents one such shape.</p>\n<h2 id="Two uses of the same syntax">Two uses of the same syntax</h2>\n<p>The ROBOT format has no fenced code blocks, so a table is also the only way to lay Robot data out in columns. That gives <code>| ... |</code> two quite different jobs, and a change that suits one can easily ruin the other.</p>\n<h3 id="Genuine tabular data">Genuine tabular data</h3>\n<p>Short keys against prose. Column widths are decided by the content, and the reader is looking things up rather than reading across.</p>\n<table border="1">\n<tr>\n<th>Name</th>\n<th>Explanation</th>\n</tr>\n<tr>\n<td>shell</td>\n<td>Whether to run the command in a shell or not.</td>\n</tr>\n<tr>\n<td>cwd</td>\n<td>Directory where to run the command.</td>\n</tr>\n<tr>\n<td>env</td>\n<td>Environment variables as a dictionary.</td>\n</tr>\n<tr>\n<td>stdout</td>\n<td>Path to a file where to write standard output.</td>\n</tr>\n</table>\n<h3 id="Robot data laid out in columns">Robot data laid out in columns</h3>\n<p>Here the table is a code sample, not data. Columns carry the meaning: the reader scans down them to see which argument is which, so anything that makes a cell wrap breaks the example.</p>\n<table border="1">\n<tr>\n<td><span class="name">Run Process</span></td>\n<td>${tools}${/}prog.py</td>\n<td>argument</td>\n<td>second arg with spaces</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><span class="name">Run Process</span></td>\n<td>java</td>\n<td>-jar</td>\n<td>${jars}${/}example.jar</td>\n<td>--option</td>\n<td>value</td>\n</tr>\n<tr>\n<td>${result} =</td>\n<td><span class="name">Run Process</span></td>\n<td>program</td>\n<td>stdout=${TEMPDIR}/stdout.txt</td>\n<td></td>\n<td></td>\n</tr>\n</table>\n<p>Tables like these are common in third-party libraries, because ROBOT is the default documentation format. They are wide to begin with, which is what bounds how much the cells can be padded.</p>',
  version: "1.2.3",
  generated: "2024-01-01T00:00:00+00:00",
  type: "LIBRARY",
  scope: "GLOBAL",
  docFormat: "HTML",
  source: "src/web/libdoc/DevLibraryRobotFormat.py",
  lineno: 12,
  tags: ["getter", "table"],
  inits: [],
  keywords: [
    {
      name: "Data Table With Header Row",
      doc: '<p>Documents a table whose first row is a header.</p>\n<p>Header cells are written as <code>= Name =</code>, which is the only way the ROBOT format marks them. Authors usually pad the source so the pipes line up, and that padding is lost in HTML, so the rendered header cannot rely on it.</p>\n<table border="1">\n<tr>\n<th>Setting</th>\n<th>Default</th>\n<th>Explanation</th>\n</tr>\n<tr>\n<td>timeout</td>\n<td>10 seconds</td>\n<td>How long to wait before giving up.</td>\n</tr>\n<tr>\n<td>retries</td>\n<td>3</td>\n<td>How many times to try again after a failure.</td>\n</tr>\n<tr>\n<td>encoding</td>\n<td>UTF-8</td>\n<td>Encoding used when reading command output.</td>\n</tr>\n</table>',
      shortdoc: "Documents a table whose first row is a header.",
      args: [
        {
          name: "name",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "name: str",
        },
        {
          name: "value",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "value: str = ",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 58,
    },
    {
      name: "Headings And Lists",
      doc: '<p>Documents the block formatting the ROBOT format supports.</p>\n<h3 id="A heading inside a keyword">A heading inside a keyword</h3>\n<p>Headings are written with <code>=</code> signs around them, one to three deep.</p>\n<ul>\n<li>An unordered item.</li>\n<li>Another item, long enough to show what happens when the text is wider than the column it is set in and has to wrap onto a second line.</li>\n</ul>\n<hr>\n<p>The ruler above is three or more hyphens on a line of their own.</p>',
      shortdoc: "Documents the block formatting the ROBOT format supports.",
      args: [
        {
          name: "items",
          doc: "",
          type: {
            name: "list",
            typedoc: "list",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "items: list",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 137,
    },
    {
      name: "Inline Formatting",
      doc: '<p>Documents the inline formatting the ROBOT format supports.</p>\n<p>Text can be <b>bold</b>, <i>italic</i>, and <code>code</code>. URLs such as <a href="http://robotframework.org">http://robotframework.org</a> are linked automatically, and so are links written as <a href="http://robotframework.org">a labelled link</a>.</p>\n<p>Keyword names in backticks link to the keyword, like <a href="#Ragged%20Table" title="&quot;Ragged Table&quot; keyword" class="name">Ragged Table</a>, and the same syntax inside a table cell has to keep working.</p>\n<table border="1">\n<tr>\n<th>Written as</th>\n<th>Renders as</th>\n</tr>\n<tr>\n<td><code>*bold*</code></td>\n<td><b>bold</b></td>\n</tr>\n<tr>\n<td><code>_italic_</code></td>\n<td><i>italic</i></td>\n</tr>\n<tr>\n<td>double backticks</td>\n<td><code>code</code></td>\n</tr>\n</table>',
      shortdoc: "Documents the inline formatting the ROBOT format supports.",
      args: [
        {
          name: "text",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "text: str",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 121,
    },
    {
      name: "Keyword With Return Value",
      doc: "<p>Returns a value, so the return table is rendered.</p>",
      shortdoc: "Returns a value, so the return table is rendered.",
      args: [
        {
          name: "name",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "name: str",
        },
      ],
      returnType: {
        name: "str",
        typedoc: "string",
        nested: [],
        union: false,
        alias: null,
      },
      returnDoc: "",
      raises: {},
      tags: ["getter"],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 161,
    },
    {
      name: "Plain Keyword With Arguments",
      doc: "<p>Takes several kinds of argument and documents none of them.</p>\n<p>Most keywords in most libraries look like this. The fixture needs a few so that the pages it renders have the proportions of real documentation rather than those of a test harness.</p>",
      shortdoc: "Takes several kinds of argument and documents none of them.",
      args: [
        {
          name: "first",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "first",
        },
        {
          name: "second",
          doc: "",
          type: null,
          defaultValue: "default",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "second=default",
        },
        {
          name: "rest",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "VAR_POSITIONAL",
          required: false,
          repr: "*rest",
        },
        {
          name: "config",
          doc: "",
          type: null,
          defaultValue: null,
          kind: "VAR_NAMED",
          required: false,
          repr: "**config",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: [],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 153,
    },
    {
      name: "Ragged Table",
      doc: '<p>Documents a table whose rows do not all have the same number of cells.</p>\n<p>Nothing stops an author writing one, and Libdoc pads the short rows with empty cells rather than rejecting them. The padding cells are what this case is here to show: they are real cells and they take the same borders and background as any other.</p>\n<table border="1">\n<tr>\n<th>Kind</th>\n<th>Note</th>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td>One cell</td>\n<td></td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td>Two cells</td>\n<td>second</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td>Three cells</td>\n<td>second</td>\n<td>third</td>\n<td></td>\n</tr>\n<tr>\n<td>Four cells</td>\n<td>second</td>\n<td>third</td>\n<td>fourth</td>\n</tr>\n</table>',
      shortdoc:
        "Documents a table whose rows do not all have the same number of cells.",
      args: [
        {
          name: "rows",
          doc: "",
          type: {
            name: "int",
            typedoc: "integer",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: "3",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "rows: int = 3",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["table"],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 87,
    },
    {
      name: "Robot Data Layout Table",
      doc: '<p>Documents a wide table used to lay Robot data out in columns.</p>\n<p>This is the shape that bounds cell padding: it is already close to the width available in a default window, and wrapping a cell destroys the column alignment that makes the example readable.</p>\n<table border="1">\n<tr>\n<td>${result} =</td>\n<td><span class="name">Run Process</span></td>\n<td>program</td>\n<td>stdout=${TEMPDIR}/stdout.txt</td>\n<td>stderr=${TEMPDIR}/stderr.txt</td>\n</tr>\n<tr>\n<td><span class="name">Log Many</span></td>\n<td>stdout: ${result.stdout}</td>\n<td>stderr: ${result.stderr}</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td>${result} =</td>\n<td><span class="name">Run Process</span></td>\n<td>program</td>\n<td>stderr=STDOUT</td>\n<td></td>\n</tr>\n</table>',
      shortdoc: "Documents a wide table used to lay Robot data out in columns.",
      args: [
        {
          name: "command",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "command: str",
        },
        {
          name: "arguments",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "VAR_POSITIONAL",
          required: false,
          repr: "*arguments: str",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["table"],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 72,
    },
    {
      name: "Table Wider Than The Page",
      doc: "<p>Documents a table too wide for the documentation column.</p>\n<p>There is no way for an author to know how wide the reader's window is, so tables that overflow are inevitable. This one overflows on purpose, which is how the frontend's handling of it stays visible while it is being worked on.</p>\n<table border=\"1\">\n<tr>\n<th>Column one</th>\n<th>Column two</th>\n<th>Column three</th>\n<th>Column four</th>\n<th>Column five</th>\n<th>Column six</th>\n</tr>\n<tr>\n<td>${VALUE_ONE}</td>\n<td>${VALUE_TWO}</td>\n<td>${VALUE_THREE}</td>\n<td>${VALUE_FOUR}</td>\n<td>${VALUE_FIVE}</td>\n<td>${VALUE_SIX}</td>\n</tr>\n<tr>\n<td>a rather long cell value</td>\n<td>another rather long cell value</td>\n<td>a third rather long value</td>\n<td>a fourth rather long value</td>\n<td>a fifth rather long value</td>\n<td>a sixth rather long value</td>\n</tr>\n</table>",
      shortdoc: "Documents a table too wide for the documentation column.",
      args: [
        {
          name: "columns",
          doc: "",
          type: {
            name: "str",
            typedoc: "string",
            nested: [],
            union: false,
            alias: null,
          },
          defaultValue: null,
          kind: "VAR_POSITIONAL",
          required: false,
          repr: "*columns: str",
        },
      ],
      returnType: null,
      returnDoc: "",
      raises: {},
      tags: ["table"],
      source: "src/web/libdoc/DevLibraryRobotFormat.py",
      lineno: 105,
    },
  ],
  typedocs: [
    {
      type: "Standard",
      name: "integer",
      doc: '<p>Conversion is done using Python\'s <a href="https://docs.python.org/library/functions.html#int">int</a> built-in function. Floating point numbers are accepted only if they can be represented as integers exactly. For example, <code>1.0</code> is accepted and <code>1.1</code> is not.</p>\n<p>It is possible to use hexadecimal, octal and binary numbers by prefixing values with <code>0x</code>, <code>0o</code> and <code>0b</code>, respectively. Spaces and underscores can be used as visual separators for digit grouping purposes.</p>\n<p>Examples: <code>42</code>, <code>-1</code>, <code>0b1010</code>, <code>10 000 000</code>, <code>0xBAD_C0FFEE</code></p>',
      usages: ["Ragged Table"],
      accepts: ["string", "float"],
    },
    {
      type: "Standard",
      name: "list",
      doc: "<p>Strings must be Python <a href=\"https://docs.python.org/library/stdtypes.html#list\">list</a> or <a href=\"https://docs.python.org/library/stdtypes.html#tuple\">tuple</a> literals. They are converted using the <a href=\"https://docs.python.org/library/ast.html#ast.literal_eval\">ast.literal_eval</a> function and possible tuples converted further to lists. They can contain any values <code>ast.literal_eval</code> supports, including lists and other collections.</p>\n<p>If the argument is a list, it is used without conversion. Tuples and other sequences are converted to lists.</p>\n<p>If the type has nested types like <code>list[int]</code>, items are converted to those types automatically.</p>\n<p>Examples: <code>['one', 'two']</code>, <code>[('one', 1), ('two', 2)]</code></p>\n<p>Support to convert nested types is new in Robot Framework 6.0. Support for tuple literals is new in Robot Framework 7.4.</p>",
      usages: ["Headings And Lists"],
      accepts: ["string", "Sequence"],
    },
    {
      type: "Standard",
      name: "string",
      doc: '<p>All arguments are converted to Unicode strings.</p>\n<p>Most values are converted simply by using <code>str(value)</code>. An exception is that bytes are mapped directly to Unicode code points with same ordinals. This means that, for example, <code>b"hyv\\xe4"</code> becomes <code>"hyvä"</code>.</p>\n<p>Converting bytes specially is new Robot Framework 7.4.</p>',
      usages: [
        "Data Table With Header Row",
        "Inline Formatting",
        "Keyword With Return Value",
        "Robot Data Layout Table",
        "Table Wider Than The Page",
      ],
      accepts: ["Any"],
    },
  ],
};

export { DATA };
